ADD : Feature updates and modifications associated with adding highlight features
backendnanodegree/Devket pull request #56
Opened 2022-12-09 12:10 UTC by wktls63

## What about is this PR? 🔍
- 하이라이트에 대한 조회, 저장, 삭제에 대한 기능이 추가 되었습니다.
   - 상세화면에서 헤더 툴바에서 '하이라이트', '즐겨 찾기' , '항목 삭제' 를 사용할 수 있도록 하는 코드를 추가 되었습니다.
   - 상세화면 사이드 바에서 하이라이트 컨텐츠 문구를 볼수 있도록 하고 해당 하이라이트를 삭제 할 수 있도록 추가 되었습니다.
   - 상세화면에서 하이라이트 삭제 시 해당 데이터와 함께 강조된 문구에 CSS를 제거하는 코드를 추가 작업이 완료 되었습니다.
   - 관련 JS 파일과 Views.py, urls.py 코드를 정리하고 가이드 주석을 추가 되었습니다. 
- mylist 화면에서 부차적인 기능이 추가되었습니다.
   - mylist  화면에서 하이라이트 탭이 활성화 되었습니다, 이제 하이라이트 탭에서 하이라이트가 적용된 항목을 조회 할 수 있습니다.
   - 비디오 항목인 경우 클릭 시 원문으로 이동하게 수정되었습니다.
- 그 외 함수, 변수 명 수정, 들여쓰기, 주석 추가 및 수정 작업

<br>

## Change Logic 📝

### before
- 상세화면에서 항목 내용을 보여주는 함수만 존재함
   - Detail 템플릿과 템플릿을 호출하는 site_detail_view 함수만 선언 되어있음
   - 사이드 바를 열고 닫을 수 있는 단순 js 토글 코드와 CSS 파일만 존재
- mylist 화면에서 하이라이트 탭이 활성화 X
- 비디오 항목 클릭 시 상세화면에서 빈 내용 값을 보여줌
- 하이라이트 관련
   - 하이라이트 관련 로직이 존재하지 않음

### after
- 하이라이트 관련 url
   - api/highlights : 하이라이트 api
   - api/highlights/<int:pk> : 각 항목에 대한 하이라이트 조회, 저장, 삭제 하는 api
   - api/highlights/list : mylist 화면 하이라이트 탭에서 ORM을 통해 하이라이트가 저장된 항목만 조회하는 api
   - api/highlights/premium/<int:pk> : 사용자 결제 여부에 따라 각 항목당 하이라이트 저장 개수를 제한하는 api

- Serializer 에 대한 수정
   - 비디오 항목 원문 이동시에 필요한 url 값을 받아오기 위해 SiteSerializer 필드에 url 값을 추가
   - HighlightSerializer 추가, 필드값은 모두 가져와야 하기 때문에 "__all__" 로 설정

- 하이라이트 views.py api class 작업
   - 상세화면에서 활성화 되는 하이라이트 조회, 저장, 삭제에 대한 HighlightAPIView 클래스 추가
      - get, post, delete 메서드 구현
   - mylist 에서 하이라이트 탭을 조회하는 HighlightListAPIView 클래스 추가
   - 결제여부에 따른 하이라이트 기능 제한을 두는 HighlightPremiumAPIView 클래스 추가
      - 유저의 결제 여부에 따른 로직을 if문으로 구현
         - 결제시 무제한, 결제상태가 아닐시 항목에 저장된 하이라이트 데이터가 3개 미만이면 저장가능, 3개 이상이면 저장 불가능
![스크린샷 2022-12-09 오후 8 48 24](https://user-images.githubusercontent.com/107481916/206696109-6a3ac907-cf41-4d2b-b383-488cc6842544.png)
         - 쿼리셋은 int로 취급되지 않아 부등호를 사용할 수 없기에 count()함수를 이용함 ( 장고에서 이런 경우에는 보편적으로 length 보다 count 함수를 사용한다고 합니다.)

- CSS
   - 하이라이트에 관한 설정값 변경

- Templates
   - detail.html에 추가 작업된 js 파일 연동
   - 헤더 툴바에서 아티클 삭제
   - 헤더 툴바 삭제 버튼에 onclick 추가
   - 클래스, id 명 추가 및 수정 작업

- JS
- detail-side-bar
   - 하이라이트 사이드바에 저장된 하이라이트 문구를 출력해주는 로직 추가
      - 삭제 버튼을 통해 해당 하이라이트 데이터를 삭제하는 기능 추가

- detail
   - 상세화면으로 이동시 저장된 하이라이트 조회하는 함수 추가
   - 헤더 툴바 기능 추가
      - 하이라이트 : 헤더 툴바 하이라이트 버튼을 이용해도 사이드 바를 열고 닫을 수 있도록 추가
      - 즐겨찾기 : 즐겨찾기 클릭 시 해당 항목을 즐겨찾기에 추가됨
         - 즐겨 찾기 클릭시 즐겨찾기가 활성화 되며 svg가 교체 되게 하는 함수를 따로 선언하여 추가함
      - 삭제 : 조회하고 있는 해당 항목을 site에서 삭제함, 연결되어 있는 하이라이터 데이터도 함께 전부 삭제

- get-site-list
   - 저장된 항목이 비디오 라면 클릭시 상세화면이 아닌 원문(새창)으로 이동하게 하는 로직 추가
 
-highlight
   - 원하는 문구를 드래그해서 저장하고 강조할수 있는 css를 적용하는 이벤트를 추가
   - 하이라이트를 저장하고 조회하는 함수 작업
   

<br>

## Screenshot 📷

### 하이라이트 탭에서 조회한 하이라이트가 적용된 항목
<img width="1160" alt="스크린샷 2022-12-09 오후 8 59 21" src="https://user-images.githubusercontent.com/107481916/206698283-9d680f1f-ba5b-4628-a489-2eae7c35e0f1.png">

### 상세화면에서 하이라이트 조회 및 상단 하이라이트 툴바 버튼으로 사이드 바를 활성화 할 수 있음
<img width="1002" alt="스크린샷 2022-12-09 오후 9 00 07" src="https://user-images.githubusercontent.com/107481916/206698444-34f62d08-d49b-4b18-a6b5-19721f468f53.png">

### 항목 삭제시 확인 문구와 함께 항목삭제 후 mylist 화면으로 이동 됨
<img width="1065" alt="스크린샷 2022-12-09 오후 9 00 22" src="https://user-images.githubusercontent.com/107481916/206698684-7ce44aa5-4c87-4c33-8d6e-76d7ff4bcae4.png">

### 하이라이트 버튼과 클릭시 하이라이트 저장과 조회 기능

### before
<img width="908" alt="스크린샷 2022-12-09 오후 9 01 09" src="https://user-images.githubusercontent.com/107481916/206698908-89d61ef1-cd77-4650-b7bb-f3b2f4bf3d47.png">

### after
<img width="994" alt="스크린샷 2022-12-09 오후 9 01 14" src="https://user-images.githubusercontent.com/107481916/206699047-5e45612d-82b0-4d35-96d6-3f3cf27c6664.png">

<br>

2022-12-09 12:50 UTC, laagom commented on pocket/models.py
> +    content_location = models.JSONField(verbose_name='컨텐츠위치', default=dict, null=True)
= 라인 맞춰주세요

2022-12-09 12:51 UTC, laagom commented on pocket/views.py
> +        print(pk)
print() 누적되면 부하가 걸립니다. 지워주세요

2022-12-09 12:52 UTC, laagom commented on pocket/views.py
> +class HighlightPremiumAPIView(APIView):
클래스간 간격은 2줄 이상 띄워주세요

2022-12-09 12:53 UTC, laagom commented on pocket/views.py
> +        """ 사용자 모델에서 결제 상태 값을 가져오는 변수 """
doc string은 함수 바로 아래 있어야 하며 doc string 아래 한줄 띄어야합니다.

2022-12-09 12:53 UTC, laagom commented on pocket/views.py
> +            return Response(True)
if 실행문 안에 코드가 없으니 라인을 붙여주는게 더 좋을 것 같습니다.

2022-12-09 12:55 UTC, laagom commented on static/js/detail-side-bar.js
> +sideToggleButton.addEventListener('click', sideToggleEvent)
굿!

2022-12-09 12:55 UTC, laagom commented on static/js/detail-side-bar.js
> +                                                    console.log(data)
console은 데이터를 확인하는 용도이기 때문에 지워주시기 바랍니다.

2022-12-09 12:56 UTC, laagom commented on static/js/detail-side-bar.js
> +const h6                                = createNode('h6')
depth 맞춰주세요 코드 읽기 힘듭니다.

2022-12-09 12:59 UTC, laagom commented on static/js/detail.js
> +    const data                          = {
```python
const data = setFetchData()
```
함수를 사용해 주세요

2022-12-09 12:59 UTC, laagom commented on static/js/detail.js
> +        const data                      = {
위와 동일합니다. 공통으로 사용하는 setFetchData함수 사용 부탁드립니다.

2022-12-09 13:23 UTC, JeHa00 requested changes

2022-12-09 13:23 UTC, JeHa00 commented on pocket/serializers.py
> +        fields = '__all__'
class Meta 가 붙어 있습니다.
class Meta 안에 등호도 줄 맞춰주세요.

이외에도 전체적으로 등호 다 맞춰주세요.

2022-12-09 13:23 UTC, JeHa00 commented on pocket/views.py
> +        print(pk)
print() 문 삭제 해주세요.

2022-12-09 13:23 UTC, JeHa00 commented on pocket/views.py
> +        user_info = User.objects.filter(id=1).values('payment_status').last()
1 말고 변수로 사용하시면 좋겠습니다.
여기서 id가 payment_status의 0 1을 의미하는 건가요?

2022-12-09 13:23 UTC, JeHa00 commented on pocket/views.py
> +        if user_info['payment_status'] == 1:
1 이라고 하기보다는
payment_success = 1 
if user_info['payment_status' ] == payment_success: 
처럼 1이 무슨 의미를 가지는지 알려주는 게 좋습니다. 
payment_success 는 사용하지 마시고, 다른 거 사용하세요. 적절하지 않고 단지 예로 설명한 겁니다.

2022-12-09 13:23 UTC, JeHa00 commented on pocket/views.py
> +        elif highlight_object < 3 :
3도 위에 1처럼 수정해주세요.

2022-12-09 13:23 UTC, JeHa00 commented on static/js/highlight.js
> +        })
위에 정수들도 최대한 변수로 사용해주세요!

2022-12-09 13:23 UTC, JeHa00 commented on static/js/detail.js
> +    const data                          = {
위에 등호 일치시켜주세요.
그리고, console.log 는 꼭 필요한가요?

2022-12-09 13:23 UTC, JeHa00 commented on static/js/detail.js
> +    let path                            = favoriteData == true ? favoritePath : noneFavoritePath
등호 일치시켜주세요~

2022-12-09 13:23 UTC, JeHa00 commented on pocket/views.py
> +        serializer.is_valid()
is_valid() 통과하지 못 했을 경우도 추가하면 좋겠어요.

2022-12-09 13:25 UTC, JeHa00 commented on pocket/views.py
> +        """ 사용자 모델에서 결제 상태 값을 가져오는 변수 """
한 줄 띄어야 하나요???

2022-12-09 14:00 UTC, wktls63 commented on pocket/views.py
> +        user_info = User.objects.filter(id=1).values('payment_status').last()
사용자 id 값 입니다, 현재 로그인해서 계정 생성하고 넘어오는게 구현이 되지 않아서 id 유저값 1을 줄수 밖에 없습닌다

2022-12-09 14:01 UTC, wktls63 commented on pocket/views.py
> +        serializer.is_valid()
지난번 병진멘토님이 말씀 해주신건데 통과 하지 못했을 경우가 발생할일이 없어서 쓸모없는 if 문이 된다고 하셨습니다. 그래서 if문을 삭제 했습니다.

2022-12-09 14:02 UTC, wktls63 commented on pocket/views.py
> +        if user_info['payment_status'] == 1:
제 생각에 저 숫자는 내부 오브젝트의 개수를 표시하는거라 정수로 표현하는게 좋은거 같습니다.

2022-12-09 14:03 UTC, wktls63 commented on pocket/models.py
> +    content_location = models.JSONField(verbose_name='컨텐츠위치', default=dict, null=True)
확인 하고 수정했습니다.

2022-12-09 14:03 UTC, wktls63 commented on pocket/views.py
> +        print(pk)
확인하고 수정 했습니다.

2022-12-09 14:04 UTC, wktls63 commented on pocket/views.py
> +class HighlightPremiumAPIView(APIView):
확인하고 수정 했습니다.

2022-12-09 14:04 UTC, wktls63 commented on pocket/views.py
> +        """ 사용자 모델에서 결제 상태 값을 가져오는 변수 """
확인하고 수정 했습니다.

2022-12-09 14:05 UTC, wktls63 commented on pocket/views.py
> +            return Response(True)
확인하고 수정 했습니다.

2022-12-09 14:05 UTC, wktls63 commented on static/js/detail-side-bar.js
> +sideToggleButton.addEventListener('click', sideToggleEvent)
good

2022-12-09 14:06 UTC, wktls63 commented on static/js/detail-side-bar.js
> +                                                    console.log(data)
확인하고 수정 했습니다.

2022-12-09 14:08 UTC, wktls63 commented on static/js/detail-side-bar.js
> +const h6                                = createNode('h6')
확인하고 수정 했습니다.

2022-12-09 14:11 UTC, wktls63 commented on static/js/detail.js
> +    const data                          = {
수정 했습니다.

2022-12-09 14:15 UTC, wktls63 commented on static/js/detail.js
> +        const data                      = {
수정 했습니다.

2022-12-09 14:15 UTC, wktls63 commented on pocket/serializers.py
> +        fields = '__all__'
수정했습니다.

2022-12-09 14:15 UTC, wktls63 commented on pocket/views.py
> +        print(pk)
삭제 됐습니다.

2022-12-09 14:17 UTC, wktls63 commented on static/js/detail.js
> +    const data                          = {
console.log 삭제 했습니다.

2022-12-09 14:18 UTC, wktls63 commented on static/js/highlight.js
> +        })
2를 나눈다는 의미라 연산자와 함께 사용 되는데 정수 사용이 좀 더 직관적이지 않을까요?

2022-12-09 14:24 UTC, wktls63 commented on static/js/detail.js
> +    let path                            = favoriteData == true ? favoritePath : noneFavoritePath
네 수정했습니다.

2022-12-09 14:37 UTC, wktls63 commented on pocket/views.py
> +        if user_info['payment_status'] == 1:
넵 그렇게 해보겠습니다.

2022-12-09 14:44 UTC, wktls63 commented on pocket/views.py
> +        elif highlight_object < 3 :
수정했습니다.

2022-12-09 14:45 UTC, wktls63 commented on static/js/highlight.js
> +        })
수정완료!

2022-12-09 15:37 UTC, yabbiya commented on static/js/highlight.js
> +function highlighClickEvent() {
highlightClickEvent가 아니라,
highlighClickEvent로 작성하신 이유가 있으신가요?

2022-12-09 15:39 UTC, yabbiya commented on static/js/highlight.js
> +    highlighClickEvent,
8번째 라인과 같습니다.

highlightClickEvent가 아니라,
highlighClickEvent로 작성하신 이유가 있으신가요?

2022-12-09 16:34 UTC, wktls63 commented on static/js/highlight.js
> +function highlighClickEvent() {
오타입니다 수정하겠습니다.

2022-12-09 16:37 UTC, wktls63 commented on static/js/highlight.js
> +    highlighClickEvent,
오타입니다 수정했습니다.

2022-12-10 05:59 UTC, JeHa00 approved these changes

2022-12-10 05:59 UTC, JeHa00 commented on pocket/views.py
> +            return Response(True)
User.objects.filter(id=1) 부분이 위에 complete_payment 가 반영되지 않았어요

2022-12-10 05:59 UTC, JeHa00 commented on static/js/highlight.js
> +        })
저렇게 한 줄씩 하는 것보다 let half, start, end; 같이 하는 게 좋지 않을까요?

2022-12-10 05:59 UTC, merged